# Generated by Django 3.1.2 on 2020-11-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_auto_20201122_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='click the link above to read article...', max_length=255),
        ),
    ]
